# Generated by Django 3.0.4 on 2020-03-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_name'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='character',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='character.Character'),
        ),
    ]
