# Generated by Django 3.0.4 on 2020-04-16 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('chat', '0003_auto_20200328_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='type',
        ),
        migrations.AddField(
            model_name='message',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Operation'),
        ),
        migrations.AddField(
            model_name='message',
            name='style',
            field=models.CharField(choices=[('pri', 'Primary'), ('sec', 'Secondary'), ('war', 'Warning')], default='pri', max_length=3),
        ),
        migrations.AddField(
            model_name='message',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('dir', 'Direct'), ('cha', 'Channel'), ('org', 'Organize'), ('tra', 'Trade'), ('glo', 'Global'), ('sys', 'System')], default='dir', max_length=3),
        ),
    ]
