# Generated by Django 3.0.4 on 2020-04-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200415_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('dir', 'Direct'), ('cha', 'Channel'), ('org', 'Organize'), ('mar', 'Market'), ('glo', 'Global'), ('sys', 'System')], default='dir', max_length=3),
        ),
    ]
