# Generated by Django 3.0.4 on 2020-04-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fri', 'Friendly'), ('hos', 'Hostile')], default='hos', max_length=3)),
                ('rank', models.CharField(choices=[('a', 'A: Does not move and harmless.'), ('b', 'B: Moves and harmless.'), ('c', 'C: Does not move and cause close range harm.'), ('d', 'D: Moves and can cause close range harm.'), ('e', 'E: Does not move and can cause long range harm.'), ('f', 'F: moves and can long range harm')], default='a', max_length=3)),
                ('name', models.CharField(default='', max_length=16, unique=True)),
                ('brute', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('finesse', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('brilliance', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('grit', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('expertise', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
    ]
