# Generated by Django 3.0.4 on 2020-04-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('type', models.CharField(choices=[('att', 'Attack'), ('mov', 'Movement'), ('sup', 'Support'), ('hea', 'Heal'), ('int', 'Interaction')], default='att', max_length=3)),
                ('range', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
    ]
