# Generated by Django 3.0.4 on 2020-03-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=16),
        ),
    ]
