# Generated by Django 3.0.4 on 2020-04-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Quirk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('description', models.TextField(default='')),
                ('perk_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perk_1', to='character.Perk')),
                ('perk_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perk_2', to='character.Perk')),
                ('perk_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perk_3', to='character.Perk')),
                ('quirk_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quirk_1', to='character.Quirk')),
                ('quirk_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quirk_2', to='character.Quirk')),
                ('quirk_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quirk_3', to='character.Quirk')),
            ],
        ),
        migrations.AddField(
            model_name='characterclass',
            name='alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Alignment'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Aspect'),
        ),
    ]
