# Generated by Django 3.0.4 on 2020-04-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20200404_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='aspect',
        ),
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Alignment'),
        ),
        migrations.AddField(
            model_name='character',
            name='aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Aspect'),
        ),
    ]
