# Generated by Django 3.0.4 on 2020-04-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20200404_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='aspect',
            name='name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='quirk',
            name='name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
