# Generated by Django 3.0.4 on 2020-04-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20200411_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect',
            name='perk_1',
        ),
        migrations.RemoveField(
            model_name='aspect',
            name='perk_2',
        ),
        migrations.RemoveField(
            model_name='aspect',
            name='perk_3',
        ),
        migrations.RemoveField(
            model_name='aspect',
            name='quirk_1',
        ),
        migrations.RemoveField(
            model_name='aspect',
            name='quirk_2',
        ),
        migrations.RemoveField(
            model_name='aspect',
            name='quirk_3',
        ),
        migrations.RemoveField(
            model_name='character',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='character',
            name='aspect',
        ),
        migrations.DeleteModel(
            name='Alignment',
        ),
        migrations.DeleteModel(
            name='Aspect',
        ),
    ]
