# Generated by Django 3.0.4 on 2020-04-16 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('character', '0006_auto_20200413_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='brilliance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='character',
            name='brute',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='character',
            name='expertise',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='character',
            name='finesse',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='character',
            name='grit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='brilliance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='brute',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='expertise',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='finesse',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='grit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.Skill')),
            ],
        ),
    ]
