# Generated by Django 3.0.4 on 2020-04-16 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MissionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('position', models.CharField(choices=[('flo', 'Floor'), ('roo', 'Roof'), ('nor', 'North'), ('eas', 'East'), ('sou', 'South'), ('wes', 'West')], default='flo', max_length=3)),
                ('visibility', models.CharField(choices=[('vis', 'Visible'), ('hid', 'Hidden'), ('inv', 'Invisible')], default='vis', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MissionRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('north', models.CharField(choices=[('wal', 'Wall'), ('doo', 'Door'), ('ope', 'Open')], default='wal', max_length=3)),
                ('east', models.CharField(choices=[('wal', 'Wall'), ('doo', 'Door'), ('ope', 'Open')], default='wal', max_length=3)),
                ('south', models.CharField(choices=[('wal', 'Wall'), ('doo', 'Door'), ('ope', 'Open')], default='wal', max_length=3)),
                ('west', models.CharField(choices=[('wal', 'Wall'), ('doo', 'Door'), ('ope', 'Open')], default='wal', max_length=3)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='MissionRoomObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.MissionObject')),
                ('mission_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.MissionRoom')),
            ],
        ),
    ]
